# Generated by Django 3.0.2 on 2020-05-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0003_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Patients',
        ),
    ]
