# Generated by Django 3.0.2 on 2020-05-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0004_auto_20200506_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
