# Generated by Django 3.0.2 on 2020-05-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0005_auto_20200506_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
