# Generated by Django 3.0.2 on 2020-05-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0008_auto_20200507_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_management.UserDetail'),
            preserve_default=False,
        ),
    ]
